### ISSUE TITLE
IDとお名前を

### ISSUE THREAD

**Issue by gs-teacher** [kyuusoku/GsApp#1]
G's のアズマです。
ID・名前が分からないので、
プロフィール欄に記載いただいて良いですか？

**Comment by kyuusoku** [comment]
ご連絡ありがとうございます。先ほどプロフィールのほう修正いたしました。49の渡辺になります。
コースはandroidになります。どうぞよろしくお願いいたします。

Date: Sun, 30 Aug 2015 20:05:40 -0700

**Comment by gs-teacher** [comment]
早速の連絡ありがとうございます。
引き続き、よろしくお願いします。
